### ISSUE TITLE
Wrong default yq version

### ISSUE THREAD

**Issue by dvdlevanon-sgh** [andrewrothstein/ansible-yq#2]
This commit added the checksum of 4.27.2 but uses default of 4.27.1

https://github.com/andrewrothstein/ansible-yq/commit/5d7cef9e33a61fcbe9b9f7c421f41e1c2f0c5e1d#diff-23e21b6c89468f7534697ad091835b3ee5e0213b37ace489488234e5a9548ec4L3

**Comment by clarkezone** [comment]
+1 this broke me as well

**Comment by andrewrothstein** [comment]
apologies. just published a new version to the galaxy defaulting to v4.27.2
