### ISSUE TITLE
yq appears broken

### ISSUE THREAD

**Issue by clarkezone** [andrewrothstein/ansible-yq#3]
TASK [andrewrothstein.yq : resolve platform specific vars] ************************************************************************************************************************************

TASK [andrewrothstein.yq : downloading https://github.com/mikefarah/yq/releases/download/v4.27.1/yq_linux_amd64 to /usr/local/bin/yq_4.27.1_linux_amd64] **************************************fatal: [100.73.194.99]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ yq_checksums[yq_ver][yq_platform] }}: 'dict object' has no attribute '4.27.1'\n\nThe error appears to be in '/home/james/.ansible/roles/andrewrothstein.yq/tasks/main.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n        - '{{ role_path }}/vars'\n- name: downloading {{ yq_url }} to {{ yq_install_exe }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

**Comment by andrewrothstein** [comment]
the mikefarah/yq repo didn't publish artifacts for [4.27.1](https://github.com/mikefarah/yq/releases/v4.27.1). Try with v4.27.5.
